version: '3'
services:
    app:
        build: docker/dev/app
        volumes:
            - ./:/var/www/html/
        networks:
            - appnet
    nginx:
        image: nginx:1.24
        volumes:
            - ./:/var/www/html
            - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - appnet
    db:
        image: postgres:15.2-alpine
        volumes:
            - ./.volumes/db/postgres:/var/lib/postgresql/data
        networks:
            - appnet
networks:
    appnet:
        driver: bridge
